config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # MOSTRAR TODOS OS PETS
  get "pets", to: "pets#index"

  # SHOW NEW FORM
  get "pets/new", to: "pets#new"

  # MOSTRAR UM PET
  get "pets/:id", to: "pets#show", as: :pet

  # CREATE PET
  post "pets", to: "pets#create"

  # MOSTRAR FORM DE EDIT
  	get "pets/:id/edit", to: "pets#edit", as: :edit

  # UPDATE PET
  patch "pets/:id", to: "pets#update"

  # DELETE PET
  delete "pets/:id", to: "pets#destroy"
  

  # resources :pets
  # resources :pets, except: [:new, :create]
  # resources :pets, only: [:index, :show]
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
	SPECIES = %w(turtle baleia pulga escorpiao dignidade)
	validates :name, presence: true
	validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
  	@pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit   
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end  
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
	<%= simple_form_for pet do |f| %>
		<%= f.input :name %>
		<%= f.input :address %>
		<%= f.input :species, collection: Pet::SPECIES %>
		<%= f.input :found_on %>
		<%= f.submit %>
	<% end %>
</div>

app/views/pets/edit.html.erb
<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<h1>Lista dos Pets Perdidos</h1>

<%= link_to "Create Pet", pets_new_path %>

<ul>
	<% @pets.each do |pet| %>
		<li> 
			<%= pet.name %> | 
			<%= pet.address %> | 
			<%= pet.species %> 
			<%= link_to "show", pet_path(pet) %> 
			<%= link_to "edit", edit_path(pet) %>
			<%= link_to "deletar", pet_path(pet), method: :delete, data: {confirm: "Are you sure?"} %>
		 </li>
	<% end %>
</ul>

app/views/pets/new.html.erb
<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<%= link_to "Back", pets_path %>

<h1> <%= @pet.name %> </h1>

<p>Address: <%= @pet.address %></p>
<p>Species: <%= @pet.species %></p>
<p>Found on: <%= @pet.found_on %></p>